spring:
  application:
    name: rpinder-batch
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
  task:
    execution:
      pool:
        core-size: 1
        max-size: 1

app:
  elasticsearch:
    host:
      - loaclhost:9200
    indcies:
      index: ring-price
      type: _doc
  crawl:
    site: http://goldgold.co.kr/charts/1_price1.php
    pattern:
      common: "body > table > tbody"
      date:
      purchase:
        gold-24k: "tr:nth-child(7) > td > table > tbody > tr:nth-child(5) > td:nth-child(2) > b"
      #        18k:
      #        14k:
      sell:
        common: "tr:nth-child(9) > td > table > tbody"
        gold-24k: "tr:nth-child(3) > td:nth-child(2) > b"
        gold-18k: "tr:nth-child(5) > td:nth-child(2)"
        gold-14k: "tr:nth-child(7) > td:nth-child(2)"
    store:
      directory: ./data


---
spring:
  profiles: local

app:
  elasticsearch:
    host:
      - loaclhost:9200


---
spring:
  profiles: develop

app:
  elasticsearch:
    host:
      - loaclhost:9200


---
spring:
  profiles: production

app:
  elasticsearch:
    host:
      - loaclhost:9200
