spring:
  application:
    name: rpinder-batch
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
  task:
    execution:
      pool:
        core-size: 1
        max-size: 1

app:
  elasticsearch:
    host:
      - loaclhost:9200
    indices:
      index: ring-price
      type: _doc
  collect:
    target: http://localhost:8080

collect:
  url: http://goldgold.co.kr/charts/1_price1.php
  query:
    dateQuery:
      - "html > body > table > tbody > tr >td >table > tbody > tr > td[height=30]"
      - "td[align=center]"
    todayGoldPriceQuery: "html > body > table > tbody > tr >td > table > tbody > tr > td > b"
  filePath: /opt/data/data.txt


---
spring:
  profiles: local

app:
  elasticsearch:
    host:
      - loaclhost:9200


---
spring:
  profiles: develop

app:
  elasticsearch:
    host:
      - loaclhost:9200


---
spring:
  profiles: production

app:
  elasticsearch:
    host:
      - loaclhost:9200
