version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    volumes:
      - $PWD/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"
networks:
  default:
    external:
      name: es-network